parametrs:
  cart.storage.session.key: cart

services:
  cart.storage.session:
    class: cart\storage\SessionStorage
    arguments: ['%cart.storage.session.key%']
    #shared: false

  cart.calculator:
    class: cart\cost\SimpleCost

  cart:
    class: cart\Cart
    arguments: ['@cart.storage.session', '@cart.calculator']
    #autowire: true